name: Node.js Du-Lua

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        NPM_CONFIG_PREFIX: "~/.npm-global"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm i -g @wolfe-labs/du-luac
      - run: mkdir -p out/development out/production
      - run: ~/.npm-global/bin/du-lua build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: du-pipe-distance.json
          path: out/production/du-pipe-distance.json
